language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

dist: trusty

before_script:
  - composer self-update
  - composer install

script:
  - vendor/bin/phpunit tests

matrix:
  allow_failures:
    - php: nightly

