language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

before_script:
  - composer self-update
  - composer install --prefer-dist -n

script:
  - ./vendor/bin/phpunit
  - ./vendor/bin/phpcs --standard=PSR2 ./src ./tests/AssetManagerTest

matrix:
  allow_failures:
    - php: nightly